CREATE TABLE IF NOT EXISTS plays (
 id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 title VARCHAR(50) NOT NULL, 
 description VARCHAR(255) NOT NULL,
 min_number INT NOT NULL,
 max_number INT NOT NULL,
 category VARCHAR(50) NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);